# Generated by Django 5.2.6 on 2026-02-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pickuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
